name: Deploy to UAT
on:
  push:
    branches:
      - uat
jobs:
  deploy-to-uat:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: >
          wget
          https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz

          mkdir ~/sfdx

          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1

          echo "$HOME/sfdx/bin" >> $GITHUB_PATH

          ~/sfdx/bin/sfdx version
      - name: Populate auth file with SFDX_URL secret of target org
        run: |
          echo ${{ secrets.UAT_URL}} > ./UAT_URL.txt
      - name: Authenticate to target Org
        run: sfdx auth:sfdxurl:store -f ./UAT_URL.txt -s -a targetOrg
      - name: Deployment 
        run: >
          source .env.uat ; sfdx force:source:deploy -p "force-app"  --testlevel RunLocalTests --json
